{
  "nome_mercado": "Macro Atacado",
  "conexoes": [
    {"origem": "Entrada", "destino": "Corredor_1_Frente", "distancia": 5},
    {"origem": "Saida_Caixas", "destino": "Corredor_6_Frente", "distancia": 5},
    {"origem": "Corredor_6_Frente", "destino": "Frios", "distancia": 8},
    {"origem": "Corredor_6_Fundo", "destino": "Acougue", "distancia": 8},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_1_Frente", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_2_Frente", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_3_Frente", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_4_Frente", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_5_Frente", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_6_Frente", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_1_Fundo", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_2_Fundo", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_3_Fundo", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_4_Fundo", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_5_Fundo", "distancia": 15},
    {"origem": "Via_Central_Horizontal", "destino": "Corredor_6_Fundo", "distancia": 15},
    {"origem": "Corredor_1_Fundo", "destino": "Via_Fundos_Dir", "distancia": 20},
    {"origem": "Corredor_2_Fundo", "destino": "Via_Fundos_Dir", "distancia": 15},
    {"origem": "Corredor_3_Fundo", "destino": "Via_Fundos_Centro", "distancia": 15},
    {"origem": "Corredor_4_Fundo", "destino": "Via_Fundos_Centro", "distancia": 15},
    {"origem": "Corredor_5_Fundo", "destino": "Via_Fundos_Esq", "distancia": 15},
    {"origem": "Corredor_6_Fundo", "destino": "Via_Fundos_Esq", "distancia": 20},
    {"origem": "Via_Fundos_Esq", "destino": "Hortifruti", "distancia": 5},
    {"origem": "Via_Fundos_Centro", "destino": "Congelados", "distancia": 5},
    {"origem": "Via_Fundos_Dir", "destino": "Via_Fundos_Centro", "distancia": 25},
    {"origem": "Via_Fundos_Centro", "destino": "Via_Fundos_Esq", "distancia": 25}
  ],
  "produtos_por_secao": {   
    "Corredor_1_Frente": ["Arroz", "Feijão", "Óleo"],
    "Corredor_1_Fundo": ["Açúcar", "Farinha", "Sal"],
    "Corredor_2_Frente": ["Macarrão", "Molho de Tomate", "Enlatados"],
    "Corredor_2_Fundo": ["Biscoito", "Salgadinho", "Chocolates"],
    "Corredor_3_Frente": ["Café", "Leite em Pó", "Achocolatado"],
    "Corredor_3_Fundo": ["Chá", "Cereais", "Mel"],
    "Corredor_4_Frente": ["Sabão em Pó", "Amaciante", "Detergente"],
    "Corredor_4_Fundo": ["Desinfetante", "Esponja", "Vassoura"],
    "Corredor_5_Frente": ["Shampoo", "Sabonete", "Desodorante"],
    "Corredor_5_Fundo": ["Creme Dental", "Papel Higiênico", "Fraldas"],
    "Corredor_6_Frente": ["Ração Cão", "Ração Gato", "Petshop"],
    "Corredor_6_Fundo": ["Bazar", "Lâmpadas", "Ferramentas"],
    "Via_Fundos_Dir": ["Cerveja", "Refrigerante", "Suco", "Água"],
    "Congelados": ["Pizza Congelada", "Hambúrguer", "Sorvete", "Batata Frita Congelada"],
    "Hortifruti": ["Banana", "Batata", "Tomate", "Cebola"],
    "Acougue": ["Carne Moída", "Frango", "Costela", "Linguiça"],
    "Frios": ["Queijo", "Presunto", "Iogurte", "Manteiga"],
    "Saida_Caixas": ["Chiclete", "Pilha"]
  }
}